### PR TITLE
Port the wasi-poll API to the new wit format.

### LINKED ISSUE #2: Remove unused errors from errno enum
Currently, witx provides [a single errno enum](https://github.com/WebAssembly/WASI/blob/main/phases/ephemeral/witx/typenames.witx#L37) that contains all of the errors across the different proposals that are currently in the WebAssembly/wasi repo.

Once WASI modularization is complete and these proposals are in different modules, we should go through and determine which errors from the errno enum are actually relevant to the functions contained in each repo. For some modules, such as wasi-clock and wasi-random, there will be very few (possibly zero) applicable errors. Other proposals, such as wasi-filesystem and wasi-poll, will have many more.

Wasi-libc will take on the task of converting the errors provided by the different modules into something usable by POSIX, etc. The work in wasi-libc will happen after the next snapshot.

### PR DESCRIPTION
**Pull request by sunfishcode**
This converts the wasi-poll repository to the new proposal template
format.

This redesigns the events and subscriptions types, to work with
interface types, and it separates monotonic from wall clocks, to
align with the current wasi-clocks proposal.

Wit is currently unable to express importing a type from another wit
file, so this proposal currently includes its own types for clocks
and file descriptors. In the future, these should be replaced with
types imported from the other wasi proposals.

This fixes #2 by eliminating the errno code returned from poll-oneoff.
It isn't needed, because poll-oneoff itself doesn't do any I/O so it
doesn't need to be able to fail.

### CODE REVIEW

**Comment by Cyborus04** [comment]
Why is the readme the same as the one in the `wasi-clocks` repo?

**Comment by sunfishcode** [comment]
Because I copied it in as a starting point but forgot to update it :-}. I'll fix it.

**Comment by sunfishcode** [comment]
Done! As with the other proposals, I haven't finished filling out all the fields yet; I'll write more docs as the proposals mature. And as with the other proposals, the CI is failing due to https://github.com/WebAssembly/wasi-tools/issues/2.

And as with the other proposals, if there are questions not answered in the README.md, please ask them!

**Comment by sunfishcode** [comment]
I'm going to go ahead and merge this now so that it's easier for people to see when they visit the repo. Please file issues if you have concerns or questions about the proposal!

**Pull request merged**
